// bebidas
export const OBTENER_BEBIDAS = 'OBTENER_BEBIDAS';
export const NUEVA_BEBIDA = 'NUEVA_BEBIDA';
export const ACTUALIZAR_BEBIDA = 'ACTUALIZAR_BEBIDA';
export const SELECCIONAR_BEBIDA = 'SELECCIONAR_BEBIDA';

// ordenes
export const SELECCIONAR_BEBIDAS = 'SELECCIONAR_BEBIDAS';
export const CANTIDAD_BEBIDAS = 'CANTIDAD_BEBIDAS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';